os: linux
dist: bionic

language: cpp

jobs:
  include:
    # Linux clang5
    - env: COMPILER=clang5 TOOLCHAIN=clang SONARCLOUD=1 PACKAGES="clang-5.0 libstdc++-5-dev libc6-dev-i386 g++-5-multilib g++-multilib"
      addons:
        sonarcloud:
          organization: "nfrechette-github"

before_install:
    - if [[ "$TOOLCHAIN" == "clang" ]]; then curl -sSL "http://apt.llvm.org/llvm-snapshot.gpg.key" | sudo -E apt-key add - ; fi
    - if [[ "$COMPILER" == "clang5" ]]; then echo "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-5.0 main" | sudo tee -a /etc/apt/sources.list > /dev/null ; fi
    - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test";
      sudo -E apt-get -yq update;
      sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install ${PACKAGES};
      fi'

script:
    # Only run sonarcloud on non-PRs
    - 'if [[ "$SONARCLOUD" == "1" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      python make.py -clean -compiler ${COMPILER} -config Release -cpu x64;
      build-wrapper-linux-x86-64 --out-dir bw_output python make.py -build -compiler ${COMPILER} -config Release -cpu x64;
      sonar-scanner;
      fi'
